env: "sc2v2"

env_args:
  map_name: null
  time_limit: 150

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 10050000

# offline collection config
num_episodes_collected: 2000
offline_data_quality: "expert"
offline_data_folder: "dataset"
save_replay_buffer: True
stop_winrate: 0.0
