# ----- marine battle setting config -----

# get env information
env: "sc2"
# get task information
task: "marine-easy-medium-replay-(10m)"
# define train tasks and test tasks
train_tasks: ["10m"]
train_tasks_data_quality: {
    "10m": "medium-replay",
}

test_tasks: ["3m", "4m", "5m", "6m", "7m", "8m", "9m", "10m", "11m", "12m"]
test_tasks_data_quality: {
}
