# ----- marine battle setting config -----

# get env information
env: "sc2"
# get task information
task: "toy0"
# define train tasks and test tasks
train_tasks: ["3m"]
train_tasks_data_quality: {
    "3m": "medium",
    "5m_vs_6m": "medium"
}

test_tasks: ["3m", "4m", "5m"]
test_tasks_data_quality: {
}
