# ----- marine battle setting config -----

# get env information
env: "sc2"
# get task information
task: "Marine"
# define train tasks and test tasks

train_tasks: ["3m", "5m_vs_6m", "9m_vs_10m"]
train_tasks_data_quality: {
    "3m": "medium",
    "5m_vs_6m": "medium",
    "9m_vs_10m": "medium",
}


test_tasks: ["3m", "5m_vs_6m", "9m_vs_10m"]
test_tasks_data_quality: {
}


pretrain_tasks: ["3m", "5m_vs_6m", "9m_vs_10m"]
pretrain_tasks_data_quality: {
    "3m": "medium",
    "5m_vs_6m": "medium",
    "9m_vs_10m": "medium",
}

